package uk.co.jcox.molglide.control

import org.apache.batik.dom.GenericDOMImplementation
import org.apache.batik.svggen.SVGGeneratorContext
import org.apache.batik.svggen.SVGGraphics2D
import org.w3c.dom.Document
import uk.co.jcox.molglide.ui.EditorPanel
import java.awt.Color
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStreamWriter
import java.io.StringWriter

class SVGExporter {

    fun quickExport(panel: EditorPanel): String {
        val domImpl = GenericDOMImplementation.getDOMImplementation()
        val svgNS = "http://www.w3.org/2000/svg"
        val document = domImpl.createDocument(svgNS, "svg", null)

        val ctx = getGenContext(document)

        val svgGenerator = SVGGraphics2D(ctx, false)
        svgGenerator.color = Color.BLACK

        panel.paintEditor(svgGenerator, false, true)
        val stringWriter = StringWriter()
        svgGenerator.stream(stringWriter)
        val output = stringWriter.toString()
        return output
    }

    private fun getGenContext(factory: Document) : SVGGeneratorContext {
        val ctx = SVGGeneratorContext.createDefault(factory)
        ctx.comment = "Generated by MolGLide https://github.com/JCox06/MolGLideX"
        return ctx
    }
}